# Generated by Django 4.0.5 on 2022-07-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=255)),
                ('schoolname', models.TextField()),
                ('standard', models.TextField()),
                ('board', models.TextField()),
                ('timeslot', models.TextField()),
            ],
        ),
    ]
