# Generated by Django 4.0.5 on 2022-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='studentdetails',
        ),
    ]
