# Generated by Django 4.0.5 on 2022-07-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edapp', '0002_prodectdetails_delete_studentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdectDetails',
        ),
    ]
